.TH 2048-QT 6 2014-05-03
.SH NAME
2048-qt \- the 2048 number game implemented in Qt
.SH SYNOPSIS
.B 2048-qt
.SH DESCRIPTION
Move the number tiles using arrow keys and merge the same numbers. Once a 2048 tile is achieved, you win.
.SH OPTIONS
2048-QT is configured graphically and does not have any commandline options.
.SH FILES
~/.config/xiaoyong/2048-Qt.conf
.RS
Per user configuration file.
.RE
.SH BUGS
If you find a bug, please notify the author.
.SH AUTHOR
Qiaoyong Zhong <solary.sh@gmail.com>
